services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:lts-community
    ports:
      - 9000:9000
    networks:
      - mynetwork
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    depends_on:
      - jenkins


  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts-jdk11
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - mynetwork
    volumes:
      - jenkins_home:/var/jenkins_home 

networks:
  mynetwork:
    external: true
    driver: bridge

volumes:
  jenkins_home:
    external: true
  sonarqube_data:
     external: true
  sonarqube_extensions:
     external: true
  sonarqube_logs:
     external: true